# TODO: currently this is unused
# These limits are used by MoveIt and augment/override the definitions in
# ur_description.
joint_limits:
  shoulder_pan_joint:
    has_acceleration_limits: true
    max_acceleration: 1.0
  shoulder_lift_joint:
    has_acceleration_limits: true
    max_acceleration: 1.0
  elbow_joint:
    has_acceleration_limits: true
    max_acceleration: 1.0
  wrist_1_joint:
    has_acceleration_limits: true
    max_acceleration: 1.0
  wrist_2_joint:
    has_acceleration_limits: true
    max_acceleration: 1.0
  wrist_3_joint:
    has_acceleration_limits: true
    max_acceleration: 1.0
