# These limits are used by MoveIt and augment/override the definitions in
# ur_description.
joint_limits:
  joint_1:
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_velocity_limits: true
    max_velocity: 0.5
  joint_2:
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_velocity_limits: true
    max_velocity: 0.5
  joint_3:
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_velocity_limits: true
    max_velocity: 0.5
  joint_4:
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_velocity_limits: true
    max_velocity: 0.5
  joint_5:
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_velocity_limits: true
    max_velocity: 0.5
  joint_6:
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_velocity_limits: true
    max_velocity: 0.5
